### ISSUE TITLE
Datetime - specifying relative time past midnight does not wrap date

### ISSUE THREAD

**Issue by brandonhorst** [lacona/lacona.github.io#2]
"Remind me to eat in 24 hours" gives "right now" rather than "1 day from now". The reason for this is because the relative `time` component ("in 24 hours") is wrapping and adding one to the date, but the `datetime` is only extracting the time component from it and ignoring the date changes.

**Comment by antonbrams** [comment]
sorry for offtop but im a huge fan of your idea and i have a little question: is it possible yet to use your application on mac desktop? If not, when it will be possible? Thanks for your work, and im realy sorry that your kickstarter company was not successful, i wish you good luck!

**Comment by brandonhorst** [comment]
Working on it! I have decided to continue work on the project, though it may be marginally slowed by my need to pursue external funding. A Mac app does not currently exist.

Details here: https://www.kickstarter.com/projects/2102999333/lacona-natural-language-commands-for-your-mac/posts/1336040

**Comment by brandonhorst** [comment]
This was fixed with the recent datetime updates - durations are now used to improve handling.
