### ISSUE TITLE
Incorrect parse, 'date' in stead of 'string' 

### ISSUE THREAD

**Issue by RowanKaag** [lacona/lacona.github.io#4]
"remind me to have dinner with my wife" right now, gives: 

remind me to have dinner with my wife's birthday

**Comment by brandonhorst** [comment]
Thanks!

This was fixed (5fe40669cac3b258a175af66017728715d8b5fc7) by ensuring that birthdays have an "on" before them. So you "remind me to call my wife" will be interpreted as a string, but "remind me to call on my wife" would be interpreted as the beginning of "remind me to call on my wife's birthday".

**Comment by RowanKaag** [comment]
Sweet! really looking forward to the end-product. There's no .app or anything available until ~January, right?

**Comment by brandonhorst** [comment]
Correct :frowning:. Working on it daily.
