### ISSUE TITLE
Feature request : use Notes Application

### ISSUE THREAD

**Issue by remirpn** [lacona/lacona.github.io#5]
Raconta is great because it's fast. Will it be possible to add quickly a brief note into the Note App ?
Great application anyway ! A sure must have.

**Comment by brandonhorst** [comment]
Definitely would love to see Notes integration, and it's pretty simple using Applescript. I'd say this is a definite.

**Comment by brandonhorst** [comment]
This issue was moved to lacona/LaconaApp#2
