### ISSUE TITLE
⌘Space in the menu bar menu is not aligned

### ISSUE THREAD

**Issue by net** [lacona/lacona.github.io#6]
The ⌘Space shortcut indicator is not aligned with the ⌘Q shortcut.
<img width="276" alt="screen shot 2016-01-29 at 6 49 49 pm" src="https://cloud.githubusercontent.com/assets/6983821/12691367/3ca20046-c6b9-11e5-9945-d90c2f770f1f.png">

**Comment by brandonhorst** [comment]
This issue was moved to lacona/LaconaApp#1
